name: Java CI Pipeline

on:      #tigger section (When does the pipeline run?)   #This defines when the workflow should run.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    #Defines a job named build
    runs-on: ubuntu-latest #specify the machine where job will run

    steps:            #Each step performs one action in the pipeline.
    - name: Checkout code #Downloads your repository code into the runner
      uses: actions/checkout@v4

    - name: Set up JDK 11   #Installs Java JDK 11 on the runner
      uses: actions/setup-java@v4  
      with:
        java-version: '11'
        distribution: 'temurin'   ##temurin is a popular OpenJDK distribution

    - name: Build with Maven
      run: mvn clean package
