name: Java CI Pipeline

on:                                  #This defines when the workflow should run.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    #Defines a job named build
    runs-on: ubuntu-latest

    steps:            #Each step performs one action in the pipeline.
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11   #Installs Java JDK 11 on the runner
      uses: actions/setup-java@v4  
      with:
        java-version: '11'
        distribution: 'temurin'   ##temurin is a popular OpenJDK distribution

    - name: Build with Maven
      run: mvn clean package
